webtalk_init -webtalk_dir E:\\PhD_project\\vivado_prjs\\mEDFLOW\\mEDFLOWAERandVGA\\mEDFLOWAERandVGA.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2022-11-03 11:50:51" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211546347_1777535269_0_465" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fdminc2ffn3humpo4ft74ajnn1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.1_24" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "24" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3991 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.224 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1667469837602" -context "sdk\\\\hardware/1667469837602"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1667469837602"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1667469837602"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1667469837602"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.1" -context "sdk\\\\hardware/1667469837602"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1667469837602"
webtalk_add_data -client sdk -key Device -value "7z035" -context "sdk\\\\hardware/1667469837602"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1667469837602"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1667469837602"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1667469837602"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1667469837602"
webtalk_add_data -client sdk -key uid -value "1667469887207" -context "sdk\\\\bsp/1667469887207"
webtalk_add_data -client sdk -key hwid -value "1667469837602" -context "sdk\\\\bsp/1667469887207"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1667469887207"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1667469887207"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1667469887207"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1667472651665"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1667472651665"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1667472651665"
webtalk_add_data -client sdk -key DebugCount -value "11" -context "sdk\\\\bsp/1667472651665"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1667472651665"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1667472651665"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1667472651665"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1667472651665"
webtalk_transmit -clientid 2161261862 -regid "211546347_1777535269_0_465" -xml E:\\PhD_project\\vivado_prjs\\mEDFLOW\\mEDFLOWAERandVGA\\mEDFLOWAERandVGA.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html E:\\PhD_project\\vivado_prjs\\mEDFLOW\\mEDFLOWAERandVGA\\mEDFLOWAERandVGA.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm E:\\PhD_project\\vivado_prjs\\mEDFLOW\\mEDFLOWAERandVGA\\mEDFLOWAERandVGA.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
