webtalk_init -webtalk_dir E:\\PhD_project\\vivado_prjs\\mEDFLOW\\mEDFLOWAERandVGA\\mEDFLOWAERandVGA.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2022-11-16 15:08:00" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211546347_1777535269_0_465" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f724go2khp134d23mufaoa0qsr" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.1_35" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "35" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3991 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.224 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1668590619078" -context "sdk\\\\application/1668590619078"
webtalk_add_data -client sdk -key hwid -value "1667469837602" -context "sdk\\\\application/1668590619078"
webtalk_add_data -client sdk -key bspid -value "1668174919464" -context "sdk\\\\application/1668590619078"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1668590619078"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1668590619078"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1668590619078"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1668590619078"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1668590619078"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1668590619078"
webtalk_add_data -client sdk -key projSize -value "972.61328125" -context "sdk\\\\application/1668590619078"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1668607680952"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1668607680952"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1668607680952"
webtalk_add_data -client sdk -key DebugCount -value "44" -context "sdk\\\\bsp/1668607680952"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1668607680952"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1668607680952"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1668607680952"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1668607680952"
webtalk_transmit -clientid 3960852274 -regid "211546347_1777535269_0_465" -xml E:\\PhD_project\\vivado_prjs\\mEDFLOW\\mEDFLOWAERandVGA\\mEDFLOWAERandVGA.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html E:\\PhD_project\\vivado_prjs\\mEDFLOW\\mEDFLOWAERandVGA\\mEDFLOWAERandVGA.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm E:\\PhD_project\\vivado_prjs\\mEDFLOW\\mEDFLOWAERandVGA\\mEDFLOWAERandVGA.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
